### ISSUE TITLE
Use link elements for clickable elements

### ISSUE THREAD

**Issue by romgrk** [pranavtharoor/micm-project-match#2]
The "Upload" element in the Profile page is using a `span`, but it is a clickable element. It should therefore be using a `a` or a `button` element.
It's important to use the right HTML element because users with disabilities sometimes cannot use the mouse, so they navigate with the keyboard. `a` and `button` are natively available for keyboard navigation (with the tab key), but not `span`. If you want to use a span as a button, you should [mark it appropriately](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role).
Also blind users usually use more advanced screen readers/helpers, and those depend on you using the correct HTML to tell the user what are the options, and where they can click.

![2019-07-24_12-50](https://user-images.githubusercontent.com/1423607/61812515-a5bfd380-ae11-11e9-9a9f-98c4e38ac140.png)

Haven't inspected everything yet, but if there are other elements with the same issue they should be fixed.

Note: my personal way to solve it is usually to have these as buttons styled as text/links, I feel button elements are more for in-app actions, and links are more for navigation.

**Comment by Kuboczoch** [comment]
There should be a `form` above this element and instead of using `span` you will use a `<input type="file"/>`

**Comment by romgrk** [comment]
The `react-dropzone` drop areas also suffer from the same issue, they don't have `role=button` so they're not clickable by users with disabilities.

The comment by @Kuboczoch about using an `<input type=file />` is relevant, note that you can always hide the native element and display whatever you want by having a `<label>` attached to it.

**Comment by romgrk** [comment]
In `/create-project`, the "Add" button for adding keywords is a div.
